# -*- coding: utf-8 -*-
"""Valuacion para github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MjH1qQNv2IX_iRIKofOX0QziTsBgIM-
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# --- CONFIGURACIÓN ---
st.set_page_config(page_title="Seminario de Valuación", layout="wide")
st.title("📊 Modelo de Valuación DCF Interactivo")

# --- BARRA LATERAL (INPUTS) ---
with st.sidebar:
    st.header("Parámetros")
    ticker = st.text_input("Ticker", value="AAPL").upper()
    metodo = st.selectbox("Método de Descuento", ["FCFF (Firma)", "FCFE (Accionista)"])
    rf = st.number_input("Tasa Libre de Riesgo (Rf)", value=0.0425, format="%.4f")
    gn = st.number_input("Crecimiento Perpetuo (g)", value=0.0300, format="%.4f")
    rating = st.selectbox("Rating Crediticio", ["AAA", "AA", "A", "BBB", "BB"])
    spreads = {"AAA": 0.005, "AA": 0.008, "A": 0.012, "BBB": 0.02, "BB": 0.04}

# --- CÁLCULOS ---
if st.button("🚀 Ejecutar Valuación"):
    try:
        stock = yf.Ticker(ticker)
        info = stock.info

        # 1. Obtener Flujos (Simplificado para el ejemplo)
        # En una app real, aquí procesarías el Statement of Cash Flows
        fcf_base = info.get('freeCashFlow', 0) / 1e6
        if fcf_base <= 0: fcf_base = 15000 # Fallback si yfinance no lo trae

        # 2. Tasas
        beta = info.get('beta', 1.1)
        ke = rf + beta * 0.05

        if metodo == "FCFF (Firma)":
            kd = (rf + spreads[rating]) * (1 - 0.21)
            mc = info.get('marketCap', 1e9); d = info.get('totalDebt', 0)
            tasa_desc = (ke * (mc/(mc+d))) + (kd * (d/(mc+d)))
            label_tasa = "WACC"
        else:
            tasa_desc = ke
            label_tasa = "Cost of Equity"

        # 3. Proyección 10 años
        proyecciones = [fcf_base * (1.08 ** i) for i in range(1, 11)]
        va_flujos = sum([f / (1 + tasa_desc)**(i+1) for i, f in enumerate(proyecciones)])

        # 4. Valor Terminal
        vt = (proyecciones[-1] * (1 + gn)) / (tasa_desc - gn)
        va_vt = vt / (1 + tasa_desc)**10

        # 5. Valor Intrínseco
        enterprise_value = va_flujos + va_vt
        cash = info.get('totalCash', 0) / 1e6
        debt = info.get('totalDebt', 0) / 1e6
        equity_value = enterprise_value + cash - debt
        shares = info.get('sharesOutstanding', 1e6) / 1e6
        precio_estimado = equity_value / shares

        # --- MOSTRAR RESULTADOS ---
        c1, c2, c3 = st.columns(3)
        c1.metric("Precio Mercado", f"${info.get('currentPrice'):.2f}")
        c2.metric("VALOR INTRÍNSECO", f"${precio_estimado:.2f}")
        c3.metric(label_tasa, f"{tasa_desc:.2%}")

        st.success(f"Análisis completado para {ticker}")

    except Exception as e:
        st.error(f"Error: {e}")